// Generated by C-Prime transpiler
#include <concepts>
#include <array>
#include "c-prime.hpp"
#include "std.hpp"
#include <cstdint>
#include <stdexcept>

CPRIME_UNSIGNED_INTEGER_TYPE(Size, cprime::uint64)

// C-Prime implemented feature showcase.

[[nodiscard]] auto imported_add(cprime::uint32 left, cprime::uint32 right) -> cprime::uint32 {
    return (left + right);
}
#include "example_native.cpp"

CPRIME_UNSIGNED_INTEGER_TYPE(DomainType, cprime::uint32)
CPRIME_COMPOSITE_TYPE(FixedDomainList, (std::array<DomainType, 3>))
CPRIME_UNSIGNED_INTEGER_TYPE(DomainTypeOfDomainType, cprime::uint32)

struct StructType {
    DomainType domain_value;
    bool primitive_value;
};

enum class EnumType : std::uint8_t {
    ENUM_VALUE_ONE,
    ENUM_VALUE_TWO,
    ENUM_VALUE_THREE
};

auto exampleFunction() -> void {
    println("This is an example function.");
}

[[nodiscard]] auto examplePrimitiveReturn() -> cprime::uint32 {
    return 42;
}

[[nodiscard]] auto exampleDomainReturn() -> DomainType {
    return 0;
}

template <typename T>
[[nodiscard]] auto templateParameterAndReturnExample(T first) -> T {
    return first;
}

template <typename T, typename U>
auto templateMultipleTypesExample(T first, U second) -> void {
    println(first);
    println(second);
}

template <typename T>
    requires(std::same_as<T, cprime::char8> || std::same_as<T, cprime::char16> || std::same_as<T, cprime::char32> || std::same_as<T, char>)
auto boundedTemplateExample(T v) -> void {
    println(v);
}

template <typename T>
    requires(std::same_as<T, cprime::char8> || std::same_as<T, cprime::char16> || std::same_as<T, cprime::char32> || std::same_as<T, char>)
auto templateUnionExample(T v) -> void {
    println(v);
}

auto exampleDiscardedFunction() -> cprime::uint32 {
    return 42;
}

[[nodiscard]] auto exampleFunctionContracts(cprime::uint32 a) -> cprime::uint32 {
    if constexpr (!((sizeof(a) == 4))) {
        throw std::runtime_error("function requires clause violated");
    }
    const cprime::uint32 value = (a * 2);
    const auto b = value;
    if (!((a > 0))) {
        throw std::runtime_error("function ensures clause violated");
    }
    return b;
}

auto examplePassByReference(cprime::reference<const cprime::uint32> value) -> void {
    println(value);
}

[[nodiscard]] auto exampleReturnByReference(cprime::reference<const cprime::uint32> value) -> cprime::reference<const cprime::uint32> {
    return value;
}

[[nodiscard]] auto main() -> int {
    println("Welcome to C-Prime!");

    exampleFunction();

    const cprime::uint32 a = examplePrimitiveReturn();
    println(a);

    const DomainType b = exampleDomainReturn();
    println(b);

    const cprime::uint32 c = templateParameterAndReturnExample(123);
    println(c);

    templateMultipleTypesExample(123, "abc");

    boundedTemplateExample('a');

    templateUnionExample('a');

    exampleDiscardedFunction();

    const cprime::uint32 e = exampleFunctionContracts(10);
    println(e);

    const cprime::reference<const cprime::uint32> f = cprime::reference(a);
    println(f);

    const cprime::reference<const cprime::uint32> g = exampleReturnByReference(f);
    println(g);
    return 0;
}
