// Generated by C-Prime transpiler
#include <array>
#include <vector>
#include <tuple>
#include "src/runtime/c-prime.hpp"
#include <utility>
#include <stdexcept>

struct Distance {
    cprime::uint32 value;

    template <typename T>
    Distance(T&& value_arg) : value(std::forward<T>(value_arg)) {
    }

    template <typename T>
    Distance& operator=(T&& value_arg) { *this = Distance(std::forward<T>(value_arg)); return *this; }

    operator cprime::uint32() const { return value; }
};
struct DistancePair {
    std::tuple<Distance, Distance> value;

    template <typename T>
    DistancePair(T&& value_arg) : value(std::forward<T>(value_arg)) {
    }

    template <typename T>
    DistancePair& operator=(T&& value_arg) { *this = DistancePair(std::forward<T>(value_arg)); return *this; }

    operator std::tuple<Distance, Distance>() const { return value; }
};
using DistanceList = std::vector<Distance>;
struct Telemetry {
    Distance altitude;
    Distance velocity;
    bool healthy;
};
enum class SystemState {
    STARTING,
    RUNNING,
    STOPPED
};
Distance next_distance(Distance value) {
    return (value + 1);
}
cprime::uint32 add_u32(cprime::uint32 left, cprime::uint32 right) {
    return (left + right);
}
void print_distance(Distance value) {
    print("distance = ");
    println(value);
}
int main() {
    const cprime::uint8 explicit_constant = 1;
    const cprime::uint8 unsigned8 = 1;
    const cprime::uint16 unsigned16 = 2;
    const cprime::uint32 unsigned32 = 3;
    const cprime::uint64 unsigned64 = 4;
    const cprime::int8 signed8 = 5;
    const cprime::int16 signed16 = 6;
    const cprime::int32 signed32 = 7;
    const cprime::int64 signed64 = 8;
    const cprime::float32 decimal32 = 1.5;
    const cprime::float64 decimal64 = 2.5;
    const cprime::char8 character8 = 'a';
    const cprime::char16 character16 = 'b';
    const cprime::char32 character32 = 'c';
    const bool enabled = true;
    cprime::uint32 counter = 0;
    counter = (counter + 1);
    counter += 2;
    counter -= 1;
    counter *= 3;
    counter /= 2;
    counter %= 5;
    const std::array<cprime::uint8, 3> fixed_numbers = {1, 2, 3};
    const std::vector<cprime::uint8> dynamic_numbers = {4, 5, 6};
    const std::tuple<cprime::uint8, cprime::float32> primitive_pair = std::make_tuple(1, 2.0);
    const Distance altitude = 1000;
    const Distance velocity = next_distance(altitude);
    const DistancePair limits = std::make_tuple(10, 20);
    const std::array<Distance, 3> checkpoints = {100, 200, 300};
    const Telemetry telemetry = {.altitude = 1000, .velocity = 42, .healthy = true};
    const SystemState state = SystemState::RUNNING;
    const cprime::uint32 total = add_u32(unsigned32, counter);
    const bool has_distance = (altitude > 0);
    const bool should_print = (has_distance && enabled);
    print("Hello, ");
    println("from C-Prime!");
    print_distance(velocity);
    if (should_print) {
        println(total);
    }
    while ((counter < 4)) {
        counter += 1;
        if ((counter == 2)) {
            continue;
        }
        println(counter);
        if ((counter == 3)) {
            break;
        }
    }
    for (cprime::uint32 index = 0; (index < 3); index += 1) {
        println(index);
    }
    cprime::uint32* const raw_pointer = (&counter);
    return 0;
}
