// Generated by C-Prime transpiler

#ifndef CPRIME_RUNTIME_IO_HPP
#define CPRIME_RUNTIME_IO_HPP

// C-Prime Standard Library.

#include <type_traits>
#include <iostream>

template <typename... Args>
void print(const Args&... args) {
    (std::cout << ... << args);
}

template <typename... Args>
void println(const Args&... args) {
    print(args...);
    std::cout << '\n';
}

#endif // CPRIME_RUNTIME_IO_HPP

#include <cstdlib>

#ifndef CPRIME_RUNTIME_HPP
#define CPRIME_RUNTIME_HPP

#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <iostream>
// #include <limits>
#include <numeric>
// #include <stdexcept>
// #include <string>
#include <type_traits>
#include <utility>
#include <cstring>

// The C-Prime primitive types are strong wrappers over a standard scalar. These
// macros forward the scalar's operators onto the wrapper so a primitive (and any
// domain type built from one) behaves like its underlying type while staying a
// distinct type. Value-producing operators keep the wrapper type; a cast back to
// the underlying scalar avoids integer-promotion warnings under strict builds.
// Removes one layer of enclosing parentheses. A composite underlying type such
// as `std::array<T, Size>` carries a top-level comma, so it must be passed to
// the macros parenthesised; this unwraps it back into a usable type name.
#define CPRIME_EXPAND(...) __VA_ARGS__

// Picks a streamable representation for a wrapped value. The character-sized
// integer types are promoted so they print as numbers; a nested C-Prime wrapper
// (when a domain type's underlying is another `type`) is left alone and streams
// through its own `operator<<`. Being a template, the untaken `if constexpr`
// branch is discarded, so this stays well-formed for every underlying type.
template <typename CPrimeStreamValue>
[[nodiscard]] constexpr auto cprimeStreamable(const CPrimeStreamValue& value) {
    if constexpr (std::is_same_v<CPrimeStreamValue, unsigned char> || std::is_same_v<CPrimeStreamValue, signed char> || std::is_same_v<CPrimeStreamValue, char>) {
        return static_cast<int>(value);
    } else {
        return value;
    }
}

// The wrapper-member macros splice `Underlying` into type positions (`Underlying&&`,
// `static_cast<Underlying>`), where clang-tidy's bugprone-macro-parentheses wants
// parentheses that would be ill-formed. Callers always pass a single type name or a
// parenthesised composite unwrapped via CPRIME_EXPAND, so the check is suppressed here.
// NOLINTBEGIN(bugprone-macro-parentheses)
#define CPRIME_COMMON_CONSTRUCTORS(T, Underlying)                                                     \
  private:                                                                                            \
    Underlying value;                                                                                 \
                                                                                                      \
  public:                                                                                             \
    [[nodiscard]] explicit T() = delete;                                                              \
    [[nodiscard]] explicit T(const Underlying& value_arg) = delete;                                   \
    [[nodiscard]] constexpr T(Underlying&& value_arg) : value(std::forward<Underlying>(value_arg)) {} \
    constexpr auto operator=(Underlying&& value_arg)->T& {                                            \
        value = std::forward<Underlying>(value_arg);                                                  \
        return *this;                                                                                 \
    }                                                                                                 \
    [[nodiscard]] explicit constexpr operator Underlying() const {                                    \
        return value;                                                                                 \
    }

#define CPRIME_EQUALITY_OPERATORS(T)                               \
    [[nodiscard]] constexpr auto operator==(T other) const->bool { \
        return value == other.value;                               \
    }                                                              \
    [[nodiscard]] constexpr auto operator!=(T other) const->bool { \
        return value != other.value;                               \
    }

#define CPRIME_ORDERED_OPERATORS(T)                                \
    [[nodiscard]] constexpr auto operator<(T other) const->bool {  \
        return value < other.value;                                \
    }                                                              \
    [[nodiscard]] constexpr auto operator<=(T other) const->bool { \
        return value <= other.value;                               \
    }                                                              \
    [[nodiscard]] constexpr auto operator>(T other) const->bool {  \
        return value > other.value;                                \
    }                                                              \
    [[nodiscard]] constexpr auto operator>=(T other) const->bool { \
        return value >= other.value;                               \
    }

#define CPRIME_ARITHMETIC_INTEGER_OPERATORS(T, Underlying)                   \
    [[nodiscard]] constexpr auto operator+(T other) const->T {               \
        return T(static_cast<Underlying>(std::add_sat(value, other.value))); \
    }                                                                        \
    [[nodiscard]] constexpr auto operator-(T other) const->T {               \
        return T(static_cast<Underlying>(std::sub_sat(value, other.value))); \
    }                                                                        \
    [[nodiscard]] constexpr auto operator*(T other) const->T {               \
        return T(static_cast<Underlying>(std::mul_sat(value, other.value))); \
    }                                                                        \
    [[nodiscard]] constexpr auto operator/(T other) const->T {               \
        return T(static_cast<Underlying>(std::div_sat(value, other.value))); \
    }                                                                        \
    [[nodiscard]] constexpr auto operator%(T other) const->T {               \
        return T(static_cast<Underlying>(value % other.value));              \
    }                                                                        \
    constexpr auto operator+=(T other)->T& {                                 \
        value = static_cast<Underlying>(std::add_sat(value, other.value));   \
        return *this;                                                        \
    }                                                                        \
    constexpr auto operator-=(T other)->T& {                                 \
        value = static_cast<Underlying>(std::sub_sat(value, other.value));   \
        return *this;                                                        \
    }                                                                        \
    constexpr auto operator*=(T other)->T& {                                 \
        value = static_cast<Underlying>(std::mul_sat(value, other.value));   \
        return *this;                                                        \
    }                                                                        \
    constexpr auto operator/=(T other)->T& {                                 \
        value = static_cast<Underlying>(std::div_sat(value, other.value));   \
        return *this;                                                        \
    }                                                                        \
    constexpr auto operator%=(T other)->T& {                                 \
        value = static_cast<Underlying>(value % other.value);                \
        return *this;                                                        \
    }

#define CPRIME_ARITHMETIC_SIGNED_OPERATORS(T, Underlying) \
    [[nodiscard]] constexpr auto operator+() const->T {   \
        return *this;                                     \
    }                                                     \
    [[nodiscard]] constexpr auto operator-() const->T {   \
        return T(static_cast<Underlying>(-value));        \
    }

#define CPRIME_ARITHMETIC_FLOATING_POINT_OPERATORS(T, Underlying)         \
    [[nodiscard]] constexpr auto operator+(T other) const->T {            \
        return T(static_cast<Underlying>(value + other.value));           \
    }                                                                     \
    [[nodiscard]] constexpr auto operator-(T other) const->T {            \
        return T(static_cast<Underlying>(value - other.value));           \
    }                                                                     \
    [[nodiscard]] constexpr auto operator*(T other) const->T {            \
        return T(static_cast<Underlying>(value * other.value));           \
    }                                                                     \
    [[nodiscard]] constexpr auto operator/(T other) const->T {            \
        return T(static_cast<Underlying>(value / other.value));           \
    }                                                                     \
    [[nodiscard]] constexpr auto operator%(T other) const->T {            \
        return T(static_cast<Underlying>(std::fmod(value, other.value))); \
    }                                                                     \
    constexpr auto operator+=(T other)->T& {                              \
        value = static_cast<Underlying>(value + other.value);             \
        return *this;                                                     \
    }                                                                     \
    constexpr auto operator-=(T other)->T& {                              \
        value = static_cast<Underlying>(value - other.value);             \
        return *this;                                                     \
    }                                                                     \
    constexpr auto operator*=(T other)->T& {                              \
        value = static_cast<Underlying>(value * other.value);             \
        return *this;                                                     \
    }                                                                     \
    constexpr auto operator/=(T other)->T& {                              \
        value = static_cast<Underlying>(value / other.value);             \
        return *this;                                                     \
    }                                                                     \
    constexpr auto operator%=(T other)->T& {                              \
        value = static_cast<Underlying>(std::fmod(value, other.value));   \
        return *this;                                                     \
    }

#define CPRIME_BITWISE_OPERATORS(T, Underlying)                  \
    [[nodiscard]] constexpr auto operator&(T other) const->T {   \
        return T(static_cast<Underlying>(value & other.value));  \
    }                                                            \
    [[nodiscard]] constexpr auto operator|(T other) const->T {   \
        return T(static_cast<Underlying>(value | other.value));  \
    }                                                            \
    [[nodiscard]] constexpr auto operator^(T other) const->T {   \
        return T(static_cast<Underlying>(value ^ other.value));  \
    }                                                            \
    [[nodiscard]] constexpr auto operator~() const->T {          \
        return T(static_cast<Underlying>(~value));               \
    }                                                            \
    [[nodiscard]] constexpr auto operator<<(T other) const->T {  \
        return T(static_cast<Underlying>(value << other.value)); \
    }                                                            \
    [[nodiscard]] constexpr auto operator>>(T other) const->T {  \
        return T(static_cast<Underlying>(value >> other.value)); \
    }                                                            \
    constexpr auto operator&=(T other)->T& {                     \
        value = static_cast<Underlying>(value & other.value);    \
        return *this;                                            \
    }                                                            \
    constexpr auto operator|=(T other)->T& {                     \
        value = static_cast<Underlying>(value | other.value);    \
        return *this;                                            \
    }                                                            \
    constexpr auto operator^=(T other)->T& {                     \
        value = static_cast<Underlying>(value ^ other.value);    \
        return *this;                                            \
    }                                                            \
    constexpr auto operator<<=(T other)->T& {                    \
        value = static_cast<Underlying>(value << other.value);   \
        return *this;                                            \
    }                                                            \
    constexpr auto operator>>=(T other)->T& {                    \
        value = static_cast<Underlying>(value >> other.value);   \
        return *this;                                            \
    }

#define CPRIME_BOOLEAN_OPERATORS(T, Underlying)                 \
    [[nodiscard]] constexpr auto operator&&(T other) const->T { \
        return T(value && other.value);                         \
    }                                                           \
    [[nodiscard]] constexpr auto operator||(T other) const->T { \
        return T(value || other.value);                         \
    }                                                           \
    [[nodiscard]] constexpr auto operator!() const->T {         \
        return T(!value);                                       \
    }

// The *_MEMBERS macros are struct-body fragments: operators plus any extra
// member functions passed as trailing arguments. They are used by the *_TYPE
// macros below and are also emitted directly into a hand-written wrapper struct
// for C-Prime `type` definitions, so that struct's constructor can carry
// contracts and its `<<` can delegate to the wrapped value's own streaming.
#define CPRIME_UNSIGNED_INTEGER_MEMBERS(T, Underlying, ...)                                             \
    CPRIME_COMMON_CONSTRUCTORS(T, Underlying)                                                           \
    template <typename UnsignedIntegerLiteral>                                                          \
        requires std::is_integral_v<UnsignedIntegerLiteral>                                             \
    constexpr T(UnsignedIntegerLiteral literal) : value(static_cast<Underlying>(std::move(literal))) {} \
    CPRIME_ARITHMETIC_INTEGER_OPERATORS(T, Underlying)                                                  \
    CPRIME_BITWISE_OPERATORS(T, Underlying)                                                             \
    CPRIME_EQUALITY_OPERATORS(T)                                                                        \
    CPRIME_ORDERED_OPERATORS(T)                                                                         \
    friend auto operator<<(std::ostream& stream, const T& self)->std::ostream& {                        \
        return stream << cprimeStreamable(self.value);                                                  \
    }                                                                                                   \
    __VA_ARGS__

#define CPRIME_SIGNED_INTEGER_MEMBERS(T, Underlying, ...)                                             \
    CPRIME_COMMON_CONSTRUCTORS(T, Underlying)                                                         \
    template <typename SignedIntegerLiteral>                                                          \
        requires std::is_integral_v<SignedIntegerLiteral>                                             \
    constexpr T(SignedIntegerLiteral literal) : value(static_cast<Underlying>(std::move(literal))) {} \
    CPRIME_ARITHMETIC_INTEGER_OPERATORS(T, Underlying)                                                \
    CPRIME_ARITHMETIC_SIGNED_OPERATORS(T, Underlying)                                                 \
    CPRIME_BITWISE_OPERATORS(T, Underlying)                                                           \
    CPRIME_EQUALITY_OPERATORS(T)                                                                      \
    CPRIME_ORDERED_OPERATORS(T)                                                                       \
    friend auto operator<<(std::ostream& stream, const T& self)->std::ostream& {                      \
        return stream << cprimeStreamable(self.value);                                                \
    }                                                                                                 \
    __VA_ARGS__

#define CPRIME_FLOATING_POINT_MEMBERS(T, Underlying, ...)                                             \
    CPRIME_COMMON_CONSTRUCTORS(T, Underlying)                                                         \
    template <typename FloatingPointLiteral>                                                          \
        requires std::is_floating_point_v<FloatingPointLiteral>                                       \
    constexpr T(FloatingPointLiteral literal) : value(static_cast<Underlying>(std::move(literal))) {} \
    CPRIME_ARITHMETIC_FLOATING_POINT_OPERATORS(T, Underlying)                                         \
    CPRIME_ARITHMETIC_SIGNED_OPERATORS(T, Underlying)                                                 \
    CPRIME_EQUALITY_OPERATORS(T)                                                                      \
    CPRIME_ORDERED_OPERATORS(T)                                                                       \
    friend auto operator<<(std::ostream& stream, const T& self)->std::ostream& {                      \
        return stream << self.value;                                                                  \
    }                                                                                                 \
    __VA_ARGS__

#define CPRIME_CHARACTER_MEMBERS(T, Underlying, ...)                                              \
    CPRIME_COMMON_CONSTRUCTORS(T, Underlying)                                                     \
    template <typename CharacterLiteral>                                                          \
        requires std::is_integral_v<CharacterLiteral>                                             \
    constexpr T(CharacterLiteral literal) : value(static_cast<Underlying>(std::move(literal))) {} \
    CPRIME_BITWISE_OPERATORS(T, Underlying)                                                       \
    CPRIME_EQUALITY_OPERATORS(T)                                                                  \
    CPRIME_ORDERED_OPERATORS(T)                                                                   \
    friend auto operator<<(std::ostream& stream, const T& self)->std::ostream& {                  \
        return stream << static_cast<char>(self.value);                                           \
    }                                                                                             \
    __VA_ARGS__

#define CPRIME_BOOLEAN_MEMBERS(T, Underlying, ...)                               \
    CPRIME_COMMON_CONSTRUCTORS(T, Underlying)                                    \
    CPRIME_EQUALITY_OPERATORS(T)                                                 \
    CPRIME_BOOLEAN_OPERATORS(T, Underlying)                                      \
    friend auto operator<<(std::ostream& stream, const T& self)->std::ostream& { \
        return stream << (self.value ? "true" : "false");                        \
    }                                                                            \
    __VA_ARGS__

#define CPRIME_ARRAY_MEMBERS(ArrayType, Underlying, ...)                                                                                                         \
  private:                                                                                                                                                       \
    CPRIME_EXPAND Underlying value;                                                                                                                              \
    template <typename, std::size_t>                                                                                                                             \
    friend struct cprime::array;                                                                                                                                 \
                                                                                                                                                                 \
  public:                                                                                                                                                        \
    using UnderlyingType = typename CPRIME_EXPAND Underlying::value_type;                                                                                        \
    [[nodiscard]] explicit constexpr ArrayType() = delete;                                                                                                       \
    [[nodiscard]] explicit ArrayType(const CPRIME_EXPAND Underlying& value_arg) = delete;                                                                        \
    [[nodiscard]] explicit constexpr ArrayType(CPRIME_EXPAND Underlying&& value_arg) : value(std::move(value_arg)) {}                                            \
    template <std::size_t... CPrimeArrayIndices>                                                                                                                 \
    [[nodiscard]] explicit constexpr ArrayType(std::initializer_list<typename decltype(value)::value_type> elements, std::index_sequence<CPrimeArrayIndices...>) \
        : value{(CPrimeArrayIndices < elements.size()                                                                                                            \
                     ? *(elements.begin() + CPrimeArrayIndices)                                                                                                  \
                     : typename decltype(value)::value_type(0))...} {}                                                                                           \
    [[nodiscard]] constexpr ArrayType(std::initializer_list<typename decltype(value)::value_type> elements)                                                      \
        : ArrayType(elements, std::make_index_sequence<std::tuple_size_v<std::remove_cv_t<decltype(value)>>>()) {}                                               \
    [[nodiscard]] constexpr auto length() const -> std::size_t {                                                                                                 \
        return value.size();                                                                                                                                     \
    }                                                                                                                                                            \
    [[nodiscard]] consteval auto size() const -> std::size_t {                                                                                                   \
        return Size;                                                                                                                                             \
    }                                                                                                                                                            \
    [[nodiscard]] constexpr auto find(const UnderlyingType& chr) const -> std::size_t {                                                                          \
        return static_cast<std::size_t>(std::distance(value.begin(), std::find(value.begin(), value.end(), chr)));                                               \
    }                                                                                                                                                            \
    [[nodiscard]] constexpr auto operator[](std::size_t index)->decltype(auto) {                                                                                 \
        return value[index];                                                                                                                                     \
    }                                                                                                                                                            \
    [[nodiscard]] constexpr auto operator[](std::size_t index) const->decltype(auto) {                                                                           \
        return value[index];                                                                                                                                     \
    }                                                                                                                                                            \
    [[nodiscard]] constexpr auto operator[](std::size_t starting_index, std::size_t end_index) const->ArrayType {                                                \
        auto result = value;                                                                                                                                     \
        for (std::size_t index = starting_index; index < end_index && index < result.size(); ++index) {                                                          \
            result[index] = value[index];                                                                                                                        \
        }                                                                                                                                                        \
        return ArrayType(std::move(result));                                                                                                                     \
    }                                                                                                                                                            \
    template <std::size_t OtherSize>                                                                                                                             \
    [[nodiscard]] constexpr auto operator+(const cprime::array<UnderlyingType, OtherSize>& other) const                                                          \
        ->cprime::array<UnderlyingType, Size + OtherSize> {                                                                                                      \
        cprime::array<UnderlyingType, Size + OtherSize> result({});                                                                                              \
        std::size_t result_index = 0;                                                                                                                            \
        for (std::size_t index = 0; index < Size; ++index) {                                                                                                     \
            if (value[index] != UnderlyingType(0)) {                                                                                                             \
                result[result_index++] = value[index];                                                                                                           \
            }                                                                                                                                                    \
        }                                                                                                                                                        \
        for (std::size_t index = 0; index < OtherSize; ++index) {                                                                                                \
            if (other.value[index] != UnderlyingType(0)) {                                                                                                       \
                result[result_index++] = other.value[index];                                                                                                     \
            }                                                                                                                                                    \
        }                                                                                                                                                        \
        return result;                                                                                                                                           \
    }                                                                                                                                                            \
    [[nodiscard]] constexpr auto operator+(std::initializer_list<UnderlyingType> elements) const->ArrayType {                                                    \
        auto result = value;                                                                                                                                     \
        std::size_t index = 0;                                                                                                                                   \
        for (const auto& element : elements) {                                                                                                                   \
            if (index == result.size()) {                                                                                                                        \
                break;                                                                                                                                           \
            }                                                                                                                                                    \
            result[index++] = element;                                                                                                                           \
        }                                                                                                                                                        \
        return ArrayType(std::move(result));                                                                                                                     \
    }                                                                                                                                                            \
    [[nodiscard]] constexpr auto operator+(const UnderlyingType chr) const->ArrayType {                                                                          \
        auto result = value;                                                                                                                                     \
        if (!result.empty()) {                                                                                                                                   \
            result[0] = chr;                                                                                                                                     \
        }                                                                                                                                                        \
        return ArrayType(std::move(result));                                                                                                                     \
    }                                                                                                                                                            \
    CPRIME_EQUALITY_OPERATORS(ArrayType)                                                                                                                         \
    CPRIME_ORDERED_OPERATORS(ArrayType)                                                                                                                          \
    friend auto operator<<(std::ostream& stream, const ArrayType& self)->std::ostream& {                                                                         \
        stream << '{';                                                                                                                                           \
        for (std::size_t i = 0; i < self.value.size(); ++i) {                                                                                                    \
            if (i != 0) {                                                                                                                                        \
                stream << ", ";                                                                                                                                  \
            }                                                                                                                                                    \
            stream << self.value[i];                                                                                                                             \
        }                                                                                                                                                        \
        return stream << '}';                                                                                                                                    \
    }                                                                                                                                                            \
    __VA_ARGS__

// NOLINTBEGIN(modernize-avoid-c-arrays)
#define CPRIME_STRING_MEMBERS(StringType, Underlying, ...)                                                                                                     \
  private:                                                                                                                                                     \
    CPRIME_EXPAND Underlying value;                                                                                                                            \
    template <std::size_t, typename>                                                                                                                           \
    friend struct cprime::string;                                                                                                                              \
    template <std::size_t N, std::size_t... CPrimeStringIndices>                                                                                               \
    static constexpr auto literalToUnderlying(const char (&cstr)[N], std::index_sequence<CPrimeStringIndices...>) -> CPRIME_EXPAND Underlying {                \
        return CPRIME_EXPAND Underlying{typename CPRIME_EXPAND Underlying::UnderlyingType(CPrimeStringIndices < N - 1 ? cstr[CPrimeStringIndices] : '\0')...}; \
    }                                                                                                                                                          \
                                                                                                                                                               \
  public:                                                                                                                                                      \
    template <std::size_t N>                                                                                                                                   \
    [[nodiscard]] constexpr StringType(const char (&cstr)[N])                                                                                                  \
        : value(literalToUnderlying(cstr, std::make_index_sequence<N>{})) {}                                                                                   \
    [[nodiscard]] explicit constexpr StringType() = delete;                                                                                                    \
    [[nodiscard]] constexpr StringType(const CPRIME_EXPAND Underlying& value_arg) = delete;                                                                    \
    [[nodiscard]] constexpr StringType(CPRIME_EXPAND Underlying&& value_arg) : value(std::move(value_arg)) {}                                                  \
    [[nodiscard]] constexpr StringType(const StringType& other) : value(other.value) {}                                                                        \
    template <std::size_t OtherSize>                                                                                                                           \
    [[nodiscard]] constexpr StringType(const cprime::string<OtherSize, typename CPRIME_EXPAND Underlying::UnderlyingType>& other)                              \
        : value({}) {                                                                                                                                          \
        constexpr std::size_t copy_size = Size < OtherSize ? Size : OtherSize;                                                                                 \
        for (std::size_t index = 0; index < copy_size; ++index) {                                                                                              \
            value[index] = other.value[index];                                                                                                                 \
        }                                                                                                                                                      \
    }                                                                                                                                                          \
    CPRIME_EQUALITY_OPERATORS(StringType)                                                                                                                      \
    CPRIME_ORDERED_OPERATORS(StringType)                                                                                                                       \
    [[nodiscard]] constexpr auto operator[](std::size_t index)->decltype(auto) {                                                                               \
        return value[index];                                                                                                                                   \
    }                                                                                                                                                          \
    [[nodiscard]] constexpr auto operator[](std::size_t index) const->decltype(auto) {                                                                         \
        return value[index];                                                                                                                                   \
    }                                                                                                                                                          \
    [[nodiscard]] constexpr auto operator[](std::size_t start_index, std::size_t end_index) const->StringType {                                                \
        return StringType(value[start_index, end_index]);                                                                                                      \
    }                                                                                                                                                          \
    template <std::size_t OtherSize>                                                                                                                           \
    [[nodiscard]] constexpr auto operator+(const cprime::string<OtherSize, typename CPRIME_EXPAND Underlying::UnderlyingType>& other) const                    \
        ->cprime::string<Size + OtherSize, typename CPRIME_EXPAND Underlying::UnderlyingType> {                                                                \
        return cprime::string<Size + OtherSize, typename CPRIME_EXPAND Underlying::UnderlyingType>(value + other.value);                                       \
    }                                                                                                                                                          \
    template <std::size_t N>                                                                                                                                   \
    [[nodiscard]] constexpr auto operator+(const char (&cstr)[N]) const                                                                                        \
        ->cprime::string<Size + N - 1, typename CPRIME_EXPAND Underlying::UnderlyingType> {                                                                    \
        cprime::array<typename CPRIME_EXPAND Underlying::UnderlyingType, Size + N - 1> result({});                                                             \
        for (std::size_t index = 0; index < Size; ++index) {                                                                                                   \
            result[index] = value[index];                                                                                                                      \
        }                                                                                                                                                      \
        for (std::size_t index = 0; index < N - 1; ++index) {                                                                                                  \
            result[Size + index] = typename CPRIME_EXPAND Underlying::UnderlyingType(cstr[index]);                                                             \
        }                                                                                                                                                      \
        return cprime::string<Size + N - 1, typename CPRIME_EXPAND Underlying::UnderlyingType>(std::move(result));                                             \
    }                                                                                                                                                          \
    [[nodiscard]] constexpr auto operator+(const CPRIME_EXPAND Underlying::UnderlyingType chr) const->StringType {                                             \
        cprime::array<typename CPRIME_EXPAND Underlying::UnderlyingType, Size> result({});                                                                     \
        for (std::size_t index = 0; index < Size; ++index) {                                                                                                   \
            result[index] = value[index];                                                                                                                      \
        }                                                                                                                                                      \
        for (std::size_t index = 0; index < Size; ++index) {                                                                                                   \
            if (result[index] == typename CPRIME_EXPAND Underlying::UnderlyingType(0)) {                                                                       \
                result[index] = chr;                                                                                                                           \
                break;                                                                                                                                         \
            }                                                                                                                                                  \
        }                                                                                                                                                      \
        return StringType(std::move(result));                                                                                                                  \
    }                                                                                                                                                          \
    [[nodiscard]] friend constexpr auto operator+(const CPRIME_EXPAND Underlying::UnderlyingType chr, const StringType& str)->StringType {                     \
        return StringType(chr + str.value);                                                                                                                    \
    }                                                                                                                                                          \
    template <std::size_t N>                                                                                                                                   \
    [[nodiscard]] friend constexpr auto operator+(const char (&cstr)[N], const StringType& str)->StringType {                                                  \
        return StringType(literalToUnderlying(cstr, std::make_index_sequence<N>{}) + str.value);                                                               \
    }                                                                                                                                                          \
    [[nodiscard]] constexpr auto length() const -> std::size_t {                                                                                               \
        return this->find('\0');                                                                                                                               \
    }                                                                                                                                                          \
    [[nodiscard]] consteval auto size() const -> std::size_t {                                                                                                 \
        return Size;                                                                                                                                           \
    }                                                                                                                                                          \
    [[nodiscard]] constexpr auto find(const CPRIME_EXPAND Underlying::UnderlyingType& chr) const -> std::size_t {                                              \
        return value.find(chr);                                                                                                                                \
    }                                                                                                                                                          \
    friend auto operator<<(std::ostream& stream, const StringType& self)->std::ostream& {                                                                      \
        for (std::size_t i = 0; i < self.value.length(); i += 1) {                                                                                             \
            stream << self.value[i];                                                                                                                           \
        }                                                                                                                                                      \
        return stream;                                                                                                                                         \
    }                                                                                                                                                          \
    __VA_ARGS__
// NOLINTEND(modernize-avoid-c-arrays)

#define CPRIME_UNSIGNED_INTEGER_TYPE(T, Underlying, ...)            \
    struct T {                                                      \
        CPRIME_UNSIGNED_INTEGER_MEMBERS(T, Underlying, __VA_ARGS__) \
    };

#define CPRIME_SIGNED_INTEGER_TYPE(T, Underlying, ...)            \
    struct T {                                                    \
        CPRIME_SIGNED_INTEGER_MEMBERS(T, Underlying, __VA_ARGS__) \
    };

#define CPRIME_FLOATING_POINT_TYPE(T, Underlying, ...)            \
    struct T {                                                    \
        CPRIME_FLOATING_POINT_MEMBERS(T, Underlying, __VA_ARGS__) \
    };

#define CPRIME_CHARACTER_TYPE(T, Underlying, ...)            \
    struct T {                                               \
        CPRIME_CHARACTER_MEMBERS(T, Underlying, __VA_ARGS__) \
    };

#define CPRIME_BOOLEAN_TYPE(T, Underlying, ...)            \
    struct T {                                             \
        CPRIME_BOOLEAN_MEMBERS(T, Underlying, __VA_ARGS__) \
    };

#define CPRIME_ARRAY_TYPE(T, Underlying, ...)            \
    struct T {                                           \
        CPRIME_ARRAY_MEMBERS(T, Underlying, __VA_ARGS__) \
    };

#define CPRIME_STRING_TYPE(T, Underlying, ...)            \
    struct T {                                            \
        CPRIME_STRING_MEMBERS(T, Underlying, __VA_ARGS__) \
    };
// NOLINTEND(bugprone-macro-parentheses)

namespace cprime {
namespace primitive {
CPRIME_UNSIGNED_INTEGER_TYPE(uint8, std::uint8_t)
CPRIME_UNSIGNED_INTEGER_TYPE(uint16, std::uint16_t)
CPRIME_UNSIGNED_INTEGER_TYPE(uint32, std::uint32_t)
CPRIME_UNSIGNED_INTEGER_TYPE(uint64, std::uint64_t)

CPRIME_SIGNED_INTEGER_TYPE(int8, std::int8_t)
CPRIME_SIGNED_INTEGER_TYPE(int16, std::int16_t)
CPRIME_SIGNED_INTEGER_TYPE(int32, std::int32_t)
CPRIME_SIGNED_INTEGER_TYPE(int64, std::int64_t)

CPRIME_FLOATING_POINT_TYPE(float32, float)
CPRIME_FLOATING_POINT_TYPE(float64, double)

CPRIME_CHARACTER_TYPE(char8, std::uint8_t)
CPRIME_CHARACTER_TYPE(char16, std::uint16_t)
CPRIME_CHARACTER_TYPE(char32, std::uint32_t)

CPRIME_BOOLEAN_TYPE(boolean, bool)

} // namespace primitive

template <typename T, std::size_t Size>
CPRIME_ARRAY_TYPE(array, (std::array<T, Size>))

template <std::size_t Size, typename T = cprime::primitive::char8>
CPRIME_STRING_TYPE(string, (cprime::array<T, Size>))

} // namespace cprime

#endif // CPRIME_RUNTIME_HPP



[[nodiscard]] auto main() -> int {
    const cprime::primitive::uint64 MAX_PRIME = UINT64_MAX;
    cprime::primitive::uint64 prime_count = 1;

    for (cprime::primitive::uint64 current = 2; (current <= MAX_PRIME); current += 1) {
        cprime::primitive::boolean is_prime = true;
        for (cprime::primitive::uint64 divisor = 2; ((divisor * divisor) <= current); divisor += 1) {
            if (((current % divisor) == 0)) {
                is_prime = false;
                break;
            }
        }
        if (is_prime) {
            println(prime_count, " n'th prime: ", current);
            prime_count += 1;
        }
    }
    println("Prime count: ", prime_count);
    return EXIT_SUCCESS;
}
