// Generated by C-Prime transpiler
#include "src/runtime/c-prime.hpp"
#include <concepts>

template <typename T
, typename U>
requires (std::same_as<T, cprime::uint8> || std::same_as<T, cprime::uint16> || std::same_as<T, cprime::uint32> || std::same_as<T, cprime::uint64> || std::same_as<T, cprime::int8> || std::same_as<T, cprime::int16> || std::same_as<T, cprime::int32> || std::same_as<T, cprime::int64>) && (std::same_as<U, cprime::float32> || std::same_as<U, cprime::float64>)
T select_first(T first, U second) {
    return first;
}
int main() {
    const cprime::uint32 input = 42;
    const cprime::float32 decimal = 1.5;
    const cprime::uint32 value = select_first(input, decimal);
    println(value);
    return 0;
}
